# Generated by Django 4.0.4 on 2025-03-07 20:58

import django.contrib.auth.mixins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('estatus', models.IntegerField(choices=[(0, 'Baja'), (1, 'Activo')], default=1, verbose_name='Estatus')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha modificación')),
                ('fecha_alta', models.DateTimeField(auto_now_add=True, verbose_name='Fecha alta')),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
                'db_table': 'Grupo',
                'ordering': ['nombre'],
                'unique_together': {('nombre',)},
            },
            bases=(models.Model, django.contrib.auth.mixins.PermissionRequiredMixin),
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('venta', models.IntegerField(choices=[(0, 'NO'), (1, 'SI')], default=0, verbose_name='Vender')),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio')),
                ('estatus', models.IntegerField(choices=[(0, 'Baja'), (1, 'Activo')], default=1, verbose_name='Estatus')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='insumo/', verbose_name='Imagen del insumo')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha modificación')),
                ('fecha_alta', models.DateTimeField(auto_now_add=True, verbose_name='Fecha alta')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumo_grupo', to='producto.grupo')),
            ],
            options={
                'verbose_name': 'Insumo',
                'verbose_name_plural': 'Insumos',
                'db_table': 'Insumo',
                'ordering': ['grupo', 'nombre'],
                'unique_together': {('grupo', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Promoción')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción')),
                ('tipo_paquete', models.IntegerField(choices=[(1, 'Combo'), (2, 'Promoción')], default=1, verbose_name='Tipo')),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio')),
                ('imagen', models.IntegerField(blank=True, null=True, verbose_name='Imagen paq.')),
                ('estatus', models.IntegerField(choices=[(0, 'Baja'), (1, 'Activo')], default=1, verbose_name='Estatus')),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True, verbose_name='Inicio de promocion')),
                ('fecha_fin', models.DateTimeField(blank=True, null=True, verbose_name='Fin de promoción')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha modificación')),
                ('fecha_alta', models.DateTimeField(auto_now_add=True, verbose_name='Fecha alta')),
            ],
            options={
                'verbose_name': 'Paquete',
                'verbose_name_plural': 'Paquetes',
                'db_table': 'Paquete',
                'ordering': ['tipo_paquete', 'nombre'],
            },
            bases=(models.Model, django.contrib.auth.mixins.PermissionRequiredMixin),
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('breve', models.CharField(blank=True, max_length=255, null=True, verbose_name='Breve descripción')),
                ('tipo', models.IntegerField(choices=[(1, 'Cocina'), (2, 'Bar')], default=1, verbose_name='Tipo')),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Imagen prod.')),
                ('estatus', models.IntegerField(choices=[(0, 'Baja'), (1, 'Activo')], default=1, verbose_name='Estatus')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha modificación')),
                ('fecha_alta', models.DateTimeField(auto_now_add=True, verbose_name='Fecha alta')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'Producto',
                'ordering': ['tipo', 'nombre'],
                'unique_together': {('nombre',)},
            },
            bases=(models.Model, django.contrib.auth.mixins.PermissionRequiredMixin),
        ),
        migrations.CreateModel(
            name='PaqueteProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1, verbose_name='Cantidad de productos en el paquete')),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.paquete')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.producto')),
            ],
            options={
                'verbose_name': 'Producto del paquete',
                'verbose_name_plural': 'Productos del Paquete',
                'db_table': 'PaqueteProducto',
                'ordering': ['paquete', 'producto'],
                'unique_together': {('paquete', 'producto')},
            },
        ),
        migrations.AddField(
            model_name='paquete',
            name='productos',
            field=models.ManyToManyField(related_name='paquetes', through='producto.PaqueteProducto', to='producto.producto'),
        ),
        migrations.CreateModel(
            name='ProductoInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aplica', models.IntegerField(choices=[(1, 'Forzoso'), (2, 'Solo Uno'), (3, 'Opcional')], default=1, verbose_name='Aplica')),
                ('cantidad', models.IntegerField(default=1, verbose_name='Cantidad de insumo por producto')),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio Unitario')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.insumo')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.producto')),
            ],
            options={
                'verbose_name': 'Insumo del producto',
                'verbose_name_plural': 'Insumos del producto',
                'db_table': 'ProductoInsumo',
                'ordering': ['producto', 'insumo'],
                'unique_together': {('producto', 'insumo')},
            },
        ),
    ]
