# Generated by Django 4.0.4 on 2025-03-07 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='', max_length=255, verbose_name='Título de la Canción')),
                ('artista', models.CharField(blank=True, max_length=255, null=True, verbose_name='Artista')),
                ('estatus', models.CharField(choices=[('NO', 'NO'), ('SI', 'SI')], default='NO', max_length=2, verbose_name='Estatus')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Solicitud')),
                ('dia_contable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='pedido.diacontable')),
            ],
            options={
                'verbose_name': 'Canción',
                'verbose_name_plural': 'Canciones',
                'db_table': 'Cancion',
                'ordering': ['fecha_solicitud'],
            },
        ),
    ]
