# Generated by Django 4.0.4 on 2025-03-19 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancion',
            name='album',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Album'),
        ),
        migrations.AddField(
            model_name='cancion',
            name='uri',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Id spotify'),
        ),
    ]
