# Generated by Django 4.0.4 on 2025-03-19 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0010_alter_usuario_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'permissions': (('cocina', 'Consulta cocina'), ('bar', 'Consulta bar'), ('servicio', 'Solicitudes comanda'), ('entregas', 'Consulta entregas'), ('consultas_seguimiento', 'Consulta de seguimiento'), ('consulta_comandas', 'Consulta comandas'), ('consulta_servicios', 'Consulta de servicios'), ('catalogo', 'Consulta catálogo'), ('accesos', 'Consulta accesos'), ('abrir', 'Día abre'), ('cerrar', 'Día cierra'), ('usuarios', 'Consulta usuarios'), ('caja', 'Pago de comandas'), ('presenta', 'Muestra QR para música'), ('musica', 'Lista de complacencias'))},
        ),
    ]
