# Generated by Django 4.0.4 on 2025-03-26 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0011_alter_usuario_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'permissions': (('cocina', 'Consulta cocina'), ('bar', 'Consulta bar'), ('servicio', 'Solicitudes comanda'), ('entregas', 'Consulta entregas'), ('consultas_seguimiento', 'Consulta de seguimiento'), ('consulta_comandas', 'Consulta comandas'), ('consulta_servicios', 'Consulta de servicios'), ('catalogo', 'Consulta catálogo'), ('accesos', 'Consulta accesos'), ('abrir', 'Día abre'), ('cerrar', 'Día cierra'), ('usuarios', 'Consulta usuarios'), ('caja', 'Pago de comandas'), ('global', 'Reporte global diario'), ('complace', 'Poner canciones a clientes'), ('presenta', 'Muestra QR para música'), ('musica', 'Lista de complacencias'))},
        ),
    ]
