# Generated by Django 4.0.4 on 2025-03-07 20:58

from django.conf import settings
import django.contrib.auth.mixins
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Tipo')),
                ('especifico', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción')),
                ('cantidad', models.IntegerField(default=1, verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio unitario')),
                ('importe', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Importe')),
                ('estatus', models.IntegerField(choices=[(0, 'Cancelado'), (1, 'Por pagar'), (2, 'Pagado')], default=1, verbose_name='Estatus')),
                ('descripcion_cancela', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cancelación por')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha modificación')),
                ('fecha_alta', models.DateTimeField(auto_now_add=True, verbose_name='Fecha alta')),
            ],
            options={
                'verbose_name': 'Operación',
                'verbose_name_plural': 'Operaciones',
                'db_table': 'Caja',
                'ordering': ['comanda', '-fecha_alta'],
            },
            bases=(models.Model, django.contrib.auth.mixins.PermissionRequiredMixin),
        ),
        migrations.CreateModel(
            name='Comanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesa', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mesa')),
                ('observacion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Observación')),
                ('estatus', models.IntegerField(choices=[(0, 'Cancelado'), (1, 'Activa'), (2, 'Pre-pagada'), (3, 'Cerrada'), (4, 'Cerrada sin pagar')], default=1, verbose_name='Estatus')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha modificación')),
                ('fecha_alta', models.DateTimeField(auto_now_add=True, verbose_name='Fecha alta')),
            ],
            options={
                'verbose_name': 'Comanda',
                'verbose_name_plural': 'Comandas',
                'db_table': 'Comanda',
                'ordering': ['-dia_contable', '-fecha_alta'],
            },
        ),
        migrations.CreateModel(
            name='DiaContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estatus', models.IntegerField(choices=[(0, 'Cancelado'), (1, 'Activo'), (2, 'Cerrado')], default=1, verbose_name='Estatus')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha modificación')),
                ('fecha_alta', models.DateTimeField(auto_now_add=True, verbose_name='Fecha alta')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
            options={
                'verbose_name': 'Día contable',
                'verbose_name_plural': 'Días contable',
                'db_table': 'DiaContable',
                'ordering': ['-fecha_alta'],
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividad', models.CharField(max_length=255, verbose_name='Actividad')),
                ('fecha_alta', models.DateTimeField(auto_now_add=True, verbose_name='Fecha alta')),
                ('comanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ComandaServicio', to='pedido.comanda')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioServicio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'db_table': 'Servicio',
                'ordering': ['comanda', '-fecha_alta'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importe_efectivo', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Importe')),
                ('importe_tarjeta', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Importe')),
                ('importe_transferencia', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Importe')),
                ('estatus', models.IntegerField(choices=[(0, 'Cancelado'), (1, 'Pagado')], default=1, verbose_name='Estatus')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha modificación')),
                ('fecha_alta', models.DateTimeField(auto_now_add=True, verbose_name='Fecha alta')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UsuarioPago', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'db_table': 'Pago',
                'ordering': ['-fecha_alta'],
            },
            bases=(models.Model, django.contrib.auth.mixins.PermissionRequiredMixin),
        ),
        migrations.CreateModel(
            name='Detalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.IntegerField(choices=[(1, 'Cocina'), (2, 'Bar')], default=1, verbose_name='Tipo')),
                ('producto', models.CharField(blank=True, max_length=255, null=True, verbose_name='Producto')),
                ('especificacion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Detalle')),
                ('nota', models.CharField(max_length=255, verbose_name='Observación')),
                ('cantidad', models.IntegerField(default=1, verbose_name='Cantidad')),
                ('estatus', models.IntegerField(choices=[(0, 'Cancelado'), (1, 'Solicitado'), (2, 'Elaborado'), (3, 'Entregado'), (4, 'Cancelado elaborado'), (5, 'Cancelado difinitivo')], default=1, verbose_name='Estatus')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='Fecha modificación')),
                ('fecha_alta', models.DateTimeField(auto_now_add=True, verbose_name='Fecha alta')),
                ('caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedido.caja', verbose_name='Caja')),
                ('comanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedido.comanda', verbose_name='ComandaDetalle')),
            ],
            options={
                'verbose_name': 'Detalle',
                'verbose_name_plural': 'Detalles',
                'db_table': 'Detalle',
                'ordering': ['-fecha_alta'],
            },
            bases=(models.Model, django.contrib.auth.mixins.PermissionRequiredMixin),
        ),
        migrations.AddField(
            model_name='comanda',
            name='dia_contable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DiaContable', to='pedido.diacontable'),
        ),
        migrations.AddField(
            model_name='caja',
            name='caja_grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pedido.pago', verbose_name='Pago_grupo'),
        ),
        migrations.AddField(
            model_name='caja',
            name='comanda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedido.comanda', verbose_name='Comanda'),
        ),
    ]
