# Generated by Django 4.0.4 on 2025-03-26 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='importe_descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Descuento'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='importe_efectivo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Efectivo'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='importe_tarjeta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Tarjeta'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='importe_transferencia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Transferencia'),
        ),
    ]
