# Generated by Django 4.0.4 on 2025-03-26 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0002_pago_importe_descuento_alter_pago_importe_efectivo_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comanda',
            unique_together={('mesa', 'observacion', 'dia_contable')},
        ),
    ]
