# Generated by Django 4.0.4 on 2025-03-27 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0003_alter_comanda_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='importe_comision',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Comisión'),
        ),
    ]
